name: Build, Test, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t srk96/devops-project:${{ github.sha }} -t srk96/devops-project:latest .

      - name: Run container and test
        run: |
          docker run -d -p 5000:5000 --name test-container \
            -e DATABASE_URL=sqlite:///test.db \
            srk96/devops-project:latest
          sleep 5
          curl http://localhost:5000

      - name: Push to Docker Hub
        run: |
          docker push srk96/devops-project:${{ github.sha }}
          docker push srk96/devops-project:latest

      - name: Setup kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
          echo "KUBECONFIG=$(pwd)/kubeconfig.yaml" >> $GITHUB_ENV

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/devops-app devops-app=srk96/devops-project:${{ github.sha }}
          kubectl rollout status deployment/devops-app